TRUNCATE TABLE `0_currencies`;

ALTER TABLE `0_currencies` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;

INSERT INTO `0_currencies` (`country`, `currency`, `curr_abrev`, `curr_symbol`, `hundreds_name`, `auto_update`, `inactive`) VALUES
('Albania', 'Leke', 'ALL', 'Lek', 'Qindarkë', 0, 0),
('Uganda', 'Shilling', 'UGX', 'Sh', 'Cents', 0, 0),
('Afghanistan', 'Afghanis', 'AFN', '؋', 'Pul', 0, 0),
('Argentina', 'Pesos', 'ARS', '$', 'Centavo', 0, 0),
('Aruba', 'Florin', 'AWG', 'ƒ', 'Cents', 0, 0),
('Australia', 'AU Dollars', 'AUD', '$', 'Cents', 0, 0),
('Azerbaijan', 'New Manats', 'AZN', 'ман', 'Qəpik', 0, 0),
('Bahamas', 'Dollars', 'BSD', '$', 'Cents', 0, 0),
('Barbados', 'Dollars', 'BBD', '$', 'Cents', 0, 0),
('Belarus', 'Rubles', 'BYR', 'p.', 'Kapyeyka', 0, 0),
('Belize', 'Dollars', 'BZD', 'BZ$', 'Cents', 0, 0),
('Bermuda', 'Dollars', 'BMD', '$', 'Cents', 0, 0),
('Bolivia', 'Bolivianos', 'BOB', '$b', 'Centavo', 0, 0),
('Bosnia and Herzegovina', 'Convertible Marka', 'BAM', 'KM', 'Fening', 0, 0),
('Botswana', 'Pula''s', 'BWP', 'P', 'Thebe', 0, 0),
('Bulgaria', 'Leva', 'BGN', 'лв', 'Stotinka', 0, 0),
('Brazil', 'Reais', 'BRL', 'R$', 'Centavo', 0, 0),
('Georgia', 'Iari', 'GEL', 'ლ', 'Tetri', 0, 0),
('Brunei Darussalam', 'Dollars', 'BND', '$', 'Sen', 0, 0),
('Cambodia', 'Riels', 'KHR', '៛', 'Sen', 0, 0),
('Canada', 'CA Dollars', 'CAD', '$', 'Cents', 1, 0),
('Cayman Islands', 'Dollars', 'KYD', '$', 'Cents', 0, 0),
('Chile', 'Pesos', 'CLP', '$', 'Centavo', 0, 0),
('China', 'Yuan Renminbi', 'CNY', '¥', 'Fen', 0, 0),
('Colombia', 'Pesos', 'COP', '$', 'Centavo', 0, 0),
('Costa Rica', 'Colón', 'CRC', '₡', 'Céntimo', 0, 0),
('Croatia', 'Kuna', 'HRK', 'kn', 'Lipa', 0, 0),
('Cuba', 'Pesos', 'CUP', '₱', 'Centavo', 0, 0),
('Czech Republic', 'Koruny', 'CZK', 'Kč', 'Haléř', 0, 0),
('Denmark', 'Kroner', 'DKK', 'kr', 'Øre', 0, 0),
('Dominican Republic', 'Pesos', 'DOP ', 'RD$', 'Centavo', 0, 0),
('East Caribbean', 'Dollars', 'XCD', '$', 'Cents', 0, 0),
('Egypt', 'Pounds', 'EGP', '£', 'Piastre', 0, 0),
('Swaziland', 'lilangeni', 'SZL', 'L', 'Cents', 0, 0),
('Euro', 'Euro', 'EUR', '€', 'Cents', 1, 0),
('Falkland Islands', 'Pounds', 'FKP', '£', 'Pennies', 0, 0),
('Fiji', 'Dollars', 'FJD', '$', 'Cents', 0, 0),
('Ghana', 'Cedis', 'GHC', '¢', 'Pesewa', 0, 0),
('Gibraltar', 'Pounds', 'GIP', '£', 'Pennies', 0, 0),
('Guatemala', 'Quetzales', 'GTQ', 'Q', 'Centavo', 0, 0),
('Alderney', 'Pounds', 'GGP', '£', 'Pennies', 0, 0),
('Guyana', 'Dollars', 'GYD', '$', 'Cents', 0, 0),
('Honduras', 'Lempiras', 'HNL', 'L', 'Centavo', 0, 0),
('Hong Kong', 'Dollars', 'HKD', '$', 'Cents', 0, 0),
('Hungary', 'Forint', 'HUF', 'Ft', 'Fillér', 0, 0),
('Iceland', 'Kronur', 'ISK', 'kr', 'Eyrir', 0, 0),
('India', 'Rupees', 'INR', 'Rp', 'Paisa', 0, 0),
('Indonesia', 'Rupiahs', 'IDR', 'Rp', 'Sen', 0, 0),
('Iran', 'Rials', 'IRR', '﷼', 'Dinar', 0, 0),
('Guinea', 'Franc', 'GNF', 'Fr', 'Centime', 0, 0),
('Isle of Man', 'Pounds', 'IMP', '£', 'Pennies', 0, 0),
('Israel', 'New Shekels', 'ILS', '₪', 'Agora', 0, 0),
('Jamaica', 'Dollars', 'JMD', 'J$', 'Cents', 0, 0),
('Japan', 'Yen', 'JPY', '¥', 'Sen', 0, 0),
('Jersey', 'Pounds', 'JEP', '£', 'Pennies', 0, 0),
('Kazakhstan', 'Tenge', 'KZT', 'лв', 'Tïın', 0, 0),
('Korea (North)', 'Won', 'KPW', '₩', 'Chon', 0, 0),
('Korea (South)', 'Won', 'KRW', '₩', 'Jeon', 0, 0),
('Kyrgyzstan', 'Soms', 'KGS', 'лв', 'Tyiyn', 0, 0),
('Laos', 'Kips', 'LAK', '₭', 'Att', 0, 0),
('Morocco', 'Dirham', 'MAD', 'د.م.', 'Centime', 0, 0),
('Lebanon', 'Pounds', 'LBP', '£', 'Piastre', 0, 0),
('Liberia', 'Dollars', 'LRD', '$', 'Cents', 0, 0),
('Switzerland', 'Switzerland Francs', 'CHF', 'CHF', 'Rappen', 0, 0),
('Lithuania', 'Litai', 'LTL', 'Lt', 'Centas', 0, 0),
('Gambia, The', 'Dalasi', 'GMD', 'D', 'Butut', 0, 0),
('Macedonia', 'Denars', 'MKD', 'ден', 'Deni', 0, 0),
('Malaysia', 'Ringgits', 'MYR', 'RM', 'Sen', 0, 0),
('Mauritius', 'Rupees', 'MUR', '₨', 'Cents', 0, 0),
('Mexico', 'Pesos', 'MXN', '$', 'Centavo', 0, 0),
('Mongolia', 'Tugriks', 'MNT', '₮', 'Möngö', 0, 0),
('Mozambique', 'Meticais', 'MZN', 'MT', 'Centavo', 0, 0),
('Namibia', 'Dollars', 'NAD', '$', 'Cents', 0, 0),
('Nepal', 'Rupees', 'NPR', '₨', 'Paisa', 0, 0),
('Netherlands Antilles', 'Guilders', 'ANG', 'ƒ', 'Cents', 0, 0),
('New Zealand', 'NZ Dollars', 'NZD', '$', 'Cents', 0, 0),
('Nicaragua', 'Cordobas', 'NIO', 'C$', 'Centavo', 0, 0),
('Nigeria', 'Nairas', 'NGN', '₦', 'Kobo', 0, 0),
('Kuwait', 'Dinar', 'KWD', 'د.ك', 'Fils', 0, 0),
('Norway', 'Krone', 'NOK', 'kr', 'Øre', 0, 0),
('Oman', 'Rials', 'OMR', '﷼', 'Baisa', 0, 0),
('Pakistan', 'Rupees', 'PKR', '₨', 'Paisa', 0, 0),
('Panama', 'Balboa', 'PAB', 'B/.', 'Centésimo', 0, 0),
('Paraguay', 'Guarani', 'PYG', 'Gs', 'Céntimo', 0, 0),
('Peru', 'Nuevos Soles', 'PEN', 'S/.', 'Céntimo', 0, 0),
('Philippines', 'Pesos', 'PHP', 'Php', 'Centavo', 0, 0),
('Poland', 'Zlotych', 'PLN', 'zł', 'Grosz', 0, 0),
('Qatar', 'Rials', 'QAR', '﷼', 'Dirham', 0, 0),
('Romania', 'New Lei', 'RON', 'lei', 'Ban', 0, 0),
('Russia', 'Rubles', 'RUB', 'руб', 'Kopek', 0, 0),
('Saint Helena', 'Pounds', 'SHP', '£', 'Pennies', 0, 0),
('Saudi Arabia', 'Riyals', 'SAR', '﷼', 'Halala', 0, 0),
('Serbia', 'Dinars', 'RSD', 'Дин.', 'Para', 0, 0),
('Seychelles', 'Rupees', 'SCR', '₨', 'Cents', 0, 0),
('Singapore', 'Dollars', 'SGD', '$', 'Cents', 0, 0),
('Solomon Islands', 'Dollars', 'SBD', '$', 'Cents', 0, 0),
('Somalia', 'Shillings', 'SOS', 'S', 'Cents', 0, 0),
('South Africa', 'Rand', 'ZAR', 'R', 'Cents', 0, 0),
('Sri Lanka', 'Rupees', 'LKR', '₨', 'Cents', 0, 0),
('Sweden', 'Kronor', 'SEK', 'kr', 'Öre', 0, 0),
('Suriname', 'Dollars', 'SRD', '$', 'Cents', 0, 0),
('Syria', 'Pounds', 'SYP', '£', 'Piastre', 0, 0),
('Taiwan', 'New Dollars', 'TWD', 'NT$', 'Cents', 0, 0),
('Thailand', 'Baht', 'THB', '฿', 'Satang', 0, 0),
('Trinidad and Tobago', 'Dollars', 'TTD', 'TT$', 'Cents', 0, 0),
('Turkey', 'Lira', 'TRY', 'TL', 'Kuruş', 0, 0),
('Tuvalu', 'Dollars', 'TVD', '$', 'Cents', 0, 0),
('Ukraine', 'Hryvnia', 'UAH', '₴', 'Kopiyka', 0, 0),
('United Kingdom', 'GB Pounds', 'GBP', '£', 'Pennies', 1, 0),
('United States of America', 'US Dollars', 'USD', '$', 'Cents', 1, 0),
('Uruguay', 'Pesos', 'UYU', '$U', 'Centésimo', 0, 0),
('Uzbekistan', 'Sums', 'UZS', 'лв', 'Tiyin', 0, 0),
('Venezuela', 'Bolivares Fuertes', 'VEF', 'Bs', 'Céntimo', 0, 0),
('Vietnam', 'Dong', 'VND', '₫', 'Hào', 0, 0),
('Yemen', 'Rials', 'YER', '﷼', 'Fils', 0, 0),
('Zambia', 'Kwacha', 'ZMW', 'ZK', 'Ngwee', 0, 0),
('United Arab Emirates', 'Dirham', 'AED', 'د.إ', 'Fils', 0, 0),
('Armenia', 'Dram', 'AMD', '֏', 'Luma', 0, 0),
('Angola', 'Kwanza', 'AOA', 'Kz', 'Cêntimo', 0, 0),
('Bangladesh', 'Taka', 'BDT', '৳', 'Paisa', 0, 0),
('Bahrain', 'Dinar', 'BHD', '.د.ب', 'Fils', 0, 0),
('Burundi', 'Franc', 'BIF', 'Fr', 'Centime', 0, 0),
('Bhutan', 'Ngultrum', 'BTN', 'Nu.', 'Chetrum', 0, 0),
('Congo, Democratic Republic of the', 'Franc', 'CDF', 'Fr', 'Centime', 0, 0),
('Cape Verde', 'Escudo', 'CVE', '$', 'Centavo', 0, 0),
('Djibouti', 'Franc', 'DJF', 'Fr', 'Centime', 0, 0),
('Algeria', 'Dinar', 'DZD', 'د.ج', 'Santeem', 0, 0),
('Eritrea', 'Nakfa', 'ERN', 'Nfk', 'Cents', 0, 0),
('Ethiopia', 'Birr', 'ETB', 'Br', 'Santim', 0, 0),
('Haiti', 'Gourde', 'HTG', 'G', 'Centime', 0, 0),
('Iraq', 'Dinar', 'IQD', 'ع.د', 'Fils', 0, 0),
('Jordan', 'Dinar', 'JOD', 'د.ا', 'Piastre', 0, 0),
('Kenya', 'Shilling', 'KES', 'Sh', 'Cents', 0, 0),
('Comoros', 'Franc', 'KMF', 'Fr', 'Centime', 0, 0),
('Lesotho', 'Loti', 'LSL', 'L', 'Sente', 0, 0),
('Libya', 'Dinar', 'LYD', 'ل.د', 'Dirham', 0, 0),
('Moldova', 'Ieu', 'MDL', 'L', 'Ban', 0, 0),
('Madagascar', 'Ariary', 'MGA', 'Ar', 'Iraimbilanja', 0, 0),
('Burma', 'Kyat', 'MMK', 'Ks', 'Pya', 0, 0),
('Macau', 'Pataca', 'MOP', 'P', 'Avo', 0, 0),
('Mauritania', 'Ouguiya', 'MRO', 'UM', 'Khoums', 0, 0),
('Maldives', 'Rufiyaa', 'MVR', '.ރ', 'Laari', 0, 0),
('Malawi', 'Kwacha', 'MWK', 'MK', 'Tambala', 0, 0),
('Papua New Guinea', 'Kina', 'PGK', 'K', 'Toea', 0, 0),
('Transnistria', 'Ruble', 'PRB', 'p.', 'Kopek', 0, 0),
('Rwanda', 'Franc', 'RWF', 'Fr', 'Centime', 0, 0),
('Sudan', 'Pounds', 'SDG', '£', 'Piastre', 0, 0),
('Sierra Leone', 'Leone', 'SLL', 'Le', 'Cents', 0, 0),
('South Sudan', 'Pounds', 'SSP', '£', 'Piastre', 0, 0),
('São Tomé and Príncipe', 'Dobra', 'STD', 'Db', 'Cêntimo', 0, 0),
('Tajikistan', 'Somoni', 'TJS', 'SM', 'Diram', 0, 0),
('Turkmenistan', 'Manat', 'TMT', 'm', 'Tennesi', 0, 0),
('Tunisia', 'Dinar', 'TND', 'د.ت', 'Millime', 0, 0),
('Tonga', 'Pa''anga', 'TOP', 'T$', 'Seniti', 0, 0),
('Tanzania', 'Shilling', 'TZS', 'Sh', 'Cents', 0, 0),
('Samoa', 'Tālā', 'WST', 'T', 'Sene', 0, 0),
('Central African CFA Franc', 'Franc', 'XAF', 'Fr', 'Centime', 0, 0),
('West African CFA Franc', 'Franc', 'XOF', 'Fr', 'Centime', 0, 0),
('CFP Franc', 'Franc', 'XPF', 'Fr', 'Centime', 0, 0);
