ALTER TABLE `0_currencies` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;

TRUNCATE TABLE `0_currencies`;

INSERT INTO `0_currencies` (`country`, `currency`, `curr_abrev`, `curr_symbol`, `hundreds_name`, `auto_update`, `inactive`) VALUES
('Albania', 'Albania Lek', 'ALL', 'Lek', 'Qindarkë', 0, 0),
('Uganda', 'Uganda Shilling', 'UGX', 'Sh', 'Cents', 0, 0),
('Afghanistan', 'Afghanistan Afghani', 'AFN', '؋', 'Pul', 0, 0),
('Argentina', 'Argentina Peso', 'ARS', '$', 'Centavo', 0, 0),
('Aruba', 'Aruba Guilder', 'AWG', 'ƒ', 'Cents', 0, 0),
('Australia', 'Australia Dollar', 'AUD', '$', 'Cents', 0, 0),
('Azerbaijan', 'Azerbaijan New Manat', 'AZN', 'ман', 'Qəpik', 0, 0),
('Bahamas', 'Bahamas Dollar', 'BSD', '$', 'Cents', 0, 0),
('Barbados', 'Barbados Dollar', 'BBD', '$', 'Cents', 0, 0),
('Belarus', 'Belarus Ruble', 'BYR', 'p.', 'Kapyeyka', 0, 0),
('Belize', 'Belize Dollar', 'BZD', 'BZ$', 'Cents', 0, 0),
('Bermuda', 'Bermuda Dollar', 'BMD', '$', 'Cents', 0, 0),
('Bolivia', 'Bolivia Boliviano', 'BOB', '$b', 'Centavo', 0, 0),
('Bosnia and Herzegovina', 'Bosnia and Herzegovina Convertible Marka', 'BAM', 'KM', 'Fening', 0, 0),
('Botswana', 'Botswana Pula', 'BWP', 'P', 'Thebe', 0, 0),
('Bulgaria', 'Bulgaria Lev', 'BGN', 'лв', 'Stotinka', 0, 0),
('Brazil', 'Brazil Real', 'BRL', 'R$', 'Centavo', 0, 0),
('Georgia', 'Georgia Lari', 'GEL', 'ლ', 'Tetri', 0, 0),
('Brunei Darussalam', 'Brunei Darussalam Dollar', 'BND', '$', 'Sen', 0, 0),
('Cambodia', 'Cambodia Riel', 'KHR', '៛', 'Sen', 0, 0),
('Canada', 'Canada Dollar', 'CAD', '$', 'Cents', 1, 0),
('Cayman Islands', 'Cayman Islands Dollar', 'KYD', '$', 'Cents', 0, 0),
('Chile', 'Chile Peso', 'CLP', '$', 'Centavo', 0, 0),
('China', 'China Yuan Renminbi', 'CNY', '¥', 'Fen', 0, 0),
('Colombia', 'Colombia Peso', 'COP', '$', 'Centavo', 0, 0),
('Costa Rica', 'Costa Rica Colon', 'CRC', '₡', 'Céntimo', 0, 0),
('Croatia', 'Croatia Kuna', 'HRK', 'kn', 'Lipa', 0, 0),
('Cuba', 'Cuba Peso', 'CUP', '₱', 'Centavo', 0, 0),
('Czech Republic', 'Czech Republic Koruna', 'CZK', 'Kč', 'Haléř', 0, 0),
('Denmark', 'Denmark Krone', 'DKK', 'kr', 'Øre', 0, 0),
('Dominican Republic', 'Dominican Republic Peso', 'DOP ', 'RD$', 'Centavo', 0, 0),
('East Caribbean', 'East Caribbean Dollar', 'XCD', '$', 'Cents', 0, 0),
('Egypt', 'Egypt Pound', 'EGP', '£', 'Piastre', 0, 0),
('Swaziland', 'Swaziland Lilangeni', 'SZL', 'L', 'Cents', 0, 0),
('Euro', 'Euro', 'EUR', '€', 'Cents', 1, 0),
('Falkland Islands', 'Falkland Islands (Malvinas) Pound', 'FKP', '£', 'Pennies', 0, 0),
('Fiji', 'Fiji Dollar', 'FJD', '$', 'Cents', 0, 0),
('Ghana', 'Ghana Cedi', 'GHC', '¢', 'Pesewa', 0, 0),
('Gibraltar', 'Gibraltar Pound', 'GIP', '£', 'Pennies', 0, 0),
('Guatemala', 'Guatemala Quetzal', 'GTQ', 'Q', 'Centavo', 0, 0),
('Guernsey', 'Guernsey Pound', 'GGP', '£', 'Pennies', 0, 0),
('Guyana', 'Guyana Dollar', 'GYD', '$', 'Cents', 0, 0),
('Honduras', 'Honduras Lempira', 'HNL', 'L', 'Centavo', 0, 0),
('Hong Kong', 'Hong Kong Dollar', 'HKD', '$', 'Cents', 0, 0),
('Hungary', 'Hungary Forint', 'HUF', 'Ft', 'Fillér', 0, 0),
('Iceland', 'Iceland Krona', 'ISK', 'kr', 'Eyrir', 0, 0),
('India', 'India Rupee', 'INR', 'Rp', 'Paisa', 0, 0),
('Indonesia', 'Indonesia Rupiah', 'IDR', 'Rp', 'Sen', 0, 0),
('Iran', 'Iran Rial', 'IRR', '﷼', 'Dinar', 0, 0),
('Guinea', 'Guinea Franc', 'GNF', 'Fr', 'Centime', 0, 0),
('Isle of Man', 'Isle of Man Pound', 'IMP', '£', 'Pennies', 0, 0),
('Israel', 'Israel Shekel', 'ILS', '₪', 'Agora', 0, 0),
('Jamaica', 'Jamaica Dollar', 'JMD', 'J$', 'Cents', 0, 0),
('Japan', 'Japan Yen', 'JPY', '¥', 'Sen', 0, 0),
('Jersey', 'Jersey Pound', 'JEP', '£', 'Pennies', 0, 0),
('Kazakhstan', 'Kazakhstan Tenge', 'KZT', 'лв', 'Tïın', 0, 0),
('Korea (North)', 'Korea (North) Won', 'KPW', '₩', 'Chon', 0, 0),
('Korea (South)', 'Korea (South) Won', 'KRW', '₩', 'Jeon', 0, 0),
('Kyrgyzstan', 'Kyrgyzstan Som', 'KGS', 'лв', 'Tyiyn', 0, 0),
('Laos', 'Laos Kip', 'LAK', '₭', 'Att', 0, 0),
('Morocco', 'Morocco Dirham', 'MAD', 'د.م.', 'Centime', 0, 0),
('Lebanon', 'Lebanon Pound', 'LBP', '£', 'Piastre', 0, 0),
('Liberia', 'Liberia Dollar', 'LRD', '$', 'Cents', 0, 0),
('Switzerland', 'Switzerland Franc', 'CHF', 'CHF', 'Rappen', 0, 0),
('Lithuania', 'Lithuania Litas', 'LTL', 'Lt', 'Centas', 0, 0),
('Gambia', 'Gambia Dalasi', 'GMD', 'D', 'Butut', 0, 0),
('Macedonia', 'Macedonia Denar', 'MKD', 'ден', 'Deni', 0, 0),
('Malaysia', 'Malaysia Ringgit', 'MYR', 'RM', 'Sen', 0, 0),
('Mauritius', 'Mauritius Rupee', 'MUR', '₨', 'Cents', 0, 0),
('Mexico', 'Mexico Peso', 'MXN', '$', 'Centavo', 0, 0),
('Mongolia', 'Mongolia Tughrik', 'MNT', '₮', 'Möngö', 0, 0),
('Mozambique', 'Mozambique Metical', 'MZN', 'MT', 'Centavo', 0, 0),
('Namibia', 'Namibia Dollar', 'NAD', '$', 'Cents', 0, 0),
('Nepal', 'Nepal Rupee', 'NPR', '₨', 'Paisa', 0, 0),
('Netherlands Antilles', 'Netherlands Antilles Guilder', 'ANG', 'ƒ', 'Cents', 0, 0),
('New Zealand', 'New Zealand Dollar', 'NZD', '$', 'Cents', 0, 0),
('Nicaragua', 'Nicaragua Cordoba', 'NIO', 'C$', 'Centavo', 0, 0),
('Nigeria', 'Nigeria Naira', 'NGN', '₦', 'Kobo', 0, 0),
('Kuwait', 'Kuwait Dinar', 'KWD', 'د.ك', 'Fils', 0, 0),
('Norway', 'Norway Krone', 'NOK', 'kr', 'Øre', 0, 0),
('Oman', 'Oman Rial', 'OMR', '﷼', 'Baisa', 0, 0),
('Pakistan', 'Pakistan Rupee', 'PKR', '₨', 'Paisa', 0, 0),
('Panama', 'Panama Balboa', 'PAB', 'B/.', 'Centésimo', 0, 0),
('Paraguay', 'Paraguay Guarani', 'PYG', 'Gs', 'Céntimo', 0, 0),
('Peru', 'Peru Nuevo Sol', 'PEN', 'S/.', 'Céntimo', 0, 0),
('Philippines', 'Philippines Peso', 'PHP', 'Php', 'Centavo', 0, 0),
('Poland', 'Poland Zloty', 'PLN', 'zł', 'Grosz', 0, 0),
('Qatar', 'Qatar Riyal', 'QAR', '﷼', 'Dirham', 0, 0),
('Romania', 'Romania New Leu', 'RON', 'lei', 'Ban', 0, 0),
('Russia', 'Russia Ruble', 'RUB', 'руб', 'Kopek', 0, 0),
('Saint Helena', 'Saint Helena Pound', 'SHP', '£', 'Pennies', 0, 0),
('Saudi Arabia', 'Saudi Arabia Riyal', 'SAR', '﷼', 'Halala', 0, 0),
('Serbia', 'Serbia Dinar', 'RSD', 'Дин.', 'Para', 0, 0),
('Seychelles', 'Seychelles Rupee', 'SCR', '₨', 'Cents', 0, 0),
('Singapore', 'Singapore Dollar', 'SGD', '$', 'Cents', 0, 0),
('Solomon Islands', 'Solomon Islands Dollar', 'SBD', '$', 'Cents', 0, 0),
('Somalia', 'Somalia Shilling', 'SOS', 'S', 'Cents', 0, 0),
('South Africa', 'outh Africa Rand', 'ZAR', 'R', 'Cents', 0, 0),
('Sri Lanka', 'Sri Lanka Rupee', 'LKR', '₨', 'Cents', 0, 0),
('Sweden', 'Sweden Krona', 'SEK', 'kr', 'Öre', 0, 0),
('Suriname', 'Suriname Dollar', 'SRD', '$', 'Cents', 0, 0),
('Syria', 'Syria Pound', 'SYP', '£', 'Piastre', 0, 0),
('Taiwan', 'Taiwan New Dollar', 'TWD', 'NT$', 'Cents', 0, 0),
('Thailand', 'Thailand Baht', 'THB', '฿', 'Satang', 0, 0),
('Trinidad and Tobago', 'Trinidad and Tobago Dollar', 'TTD', 'TT$', 'Cents', 0, 0),
('Turkey', 'Turkey Lira', 'TRY', 'TL', 'Kuruş', 0, 0),
('Tuvalu', 'Tuvalu Dollar', 'TVD', '$', 'Cents', 0, 0),
('Ukraine', 'Ukraine Hryvnia', 'UAH', '₴', 'Kopiyka', 0, 0),
('United Kingdom', 'United Kingdom Pound', 'GBP', '£', 'Pennies', 1, 0),
('United States of America', 'United States Dollar', 'USD', '$', 'Cents', 1, 0),
('Uruguay', 'Uruguay Peso', 'UYU', '$U', 'Centésimo', 0, 0),
('Uzbekistan', 'Uzbekistan Som', 'UZS', 'лв', 'Tiyin', 0, 0),
('Venezuela', 'Venezuela Bolivar', 'VEF', 'Bs', 'Céntimo', 0, 0),
('Vietnam', 'Viet Nam Dong', 'VND', '₫', 'Hào', 0, 0),
('Yemen', 'Yemen Rial', 'YER', '﷼', 'Fils', 0, 0),
('Zambia', 'Zambia Kwacha', 'ZMW', 'ZK', 'Ngwee', 0, 0),
('United Arab Emirates', 'United Arab Emirates Dirham', 'AED', 'د.إ', 'Fils', 0, 0),
('Armenia', 'Armenia Dram', 'AMD', '֏', 'Luma', 0, 0),
('Angola', 'Angola Kwanza', 'AOA', 'Kz', 'Cêntimo', 0, 0),
('Bangladesh', 'Bangladesh Taka', 'BDT', '৳', 'Paisa', 0, 0),
('Bahrain', 'Bahrain Dinar', 'BHD', '.د.ب', 'Fils', 0, 0),
('Burundi', 'Burundi Franc', 'BIF', 'Fr', 'Centime', 0, 0),
('Bhutan', 'Bhutan Ngultrum', 'BTN', 'Nu.', 'Chetrum', 0, 0),
('Congo', 'Congo Franc', 'CDF', 'Fr', 'Centime', 0, 0),
('Cape Verde', 'Cape Verde Escudo', 'CVE', '$', 'Centavo', 0, 0),
('Djibouti', 'Djibouti Franc', 'DJF', 'Fr', 'Centime', 0, 0),
('Algeria', 'Algeria Dinar', 'DZD', 'د.ج', 'Santeem', 0, 0),
('Eritrea', 'Eritrea Nakfa', 'ERN', 'Nfk', 'Cents', 0, 0),
('Ethiopia', 'Ethiopia Birr', 'ETB', 'Br', 'Santim', 0, 0),
('Haiti', 'Haiti Gourde', 'HTG', 'G', 'Centime', 0, 0),
('Iraq', 'Iraq Dinar', 'IQD', 'ع.د', 'Fils', 0, 0),
('Jordan', 'Jordan Dinar', 'JOD', 'د.ا', 'Piastre', 0, 0),
('Kenya', 'Kenya Shilling', 'KES', 'Sh', 'Cents', 0, 0),
('Comoros', 'Comoros Franc', 'KMF', 'Fr', 'Centime', 0, 0),
('Lesotho', 'Lesotho Loti', 'LSL', 'L', 'Sente', 0, 0),
('Libya', 'Libya Dinar', 'LYD', 'ل.د', 'Dirham', 0, 0),
('Moldova', 'Moldova Leu', 'MDL', 'L', 'Ban', 0, 0),
('Madagascar', 'Madagascar Ariary', 'MGA', 'Ar', 'Iraimbilanja', 0, 0),
('Burma', 'Burma Kyat', 'MMK', 'Ks', 'Pya', 0, 0),
('Macau', 'Macau Pataca', 'MOP', 'P', 'Avo', 0, 0),
('Mauritania', 'Mauritania Ouguiya', 'MRO', 'UM', 'Khoums', 0, 0),
('Maldives', 'Maldives Rufiyaa', 'MVR', '.ރ', 'Laari', 0, 0),
('Malawi', 'Malawi Kwacha', 'MWK', 'MK', 'Tambala', 0, 0),
('Papua New Guinea', 'Papua New Guinea Kina', 'PGK', 'K', 'Toea', 0, 0),
('Rwanda', 'Rwanda Franc', 'RWF', 'Fr', 'Centime', 0, 0),
('Sudan', 'Sudan Pound', 'SDG', '£', 'Piastre', 0, 0),
('Sierra Leone', 'Sierra Leone Leone', 'SLL', 'Le', 'Cents', 0, 0),
('South Sudan', 'South Sudan Pounds', 'SSP', '£', 'Piastre', 0, 0),
('São Tomé and Príncipe', 'São Tomé and Príncipe Dobra', 'STD', 'Db', 'Cêntimo', 0, 0),
('Tajikistan', 'Tajikistan Somoni', 'TJS', 'SM', 'Diram', 0, 0),
('Turkmenistan', 'Turkmenistan Manat', 'TMT', 'm', 'Tennesi', 0, 0),
('Tunisia', 'Tunisia Dinar', 'TND', 'د.ت', 'Millime', 0, 0),
('Tonga', 'Tonga Paanga', 'TOP', 'T$', 'Seniti', 0, 0),
('Tanzania', 'Tanzania Shilling', 'TZS', 'Sh', 'Cents', 0, 0),
('Samoa', 'Samoa Tala', 'WST', 'T', 'Sene', 0, 0),
('Central African CFA Franc', 'Central African CFA Franc', 'XAF', 'Fr', 'Centime', 0, 0),
('West African CFA Franc', 'West African CFA Franc', 'XOF', 'Fr', 'Centime', 0, 0),
('CFP Franc', 'CFP Franc', 'XPF', 'Fr', 'Centime', 0, 0);